version: "3.8"

services:
  # 1. Database Tier
  mongodb:
    image: mongo:latest
    container_name: local-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. Event Broker Tier (Added for Catalog CQRS-Lite Sync)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: local-rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Web Management UI (Username: guest / Password: guest)
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # 3. Email Interceptor Tier
  mailpit:
    image: axllent/mailpit
    container_name: local-mailpit
    ports:
      - "1025:1025" # SMTP Port
      - "8025:8025" # Web UI Port

  # 4. Application Tier
  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./apps/user-service/.env.dev
    depends_on:
      - mongodb
      - mailpit

  catalog-service:
    build:
      context: .
      dockerfile: apps/catalog-service/Dockerfile
    container_name: catalog-service
    env_file:
      - ./apps/catalog-service/.env.dev
    depends_on:
      - mongodb
      - rabbitmq

  # 5. Gateway Tier
  api-gateway:
    image: envoyproxy/envoy:v1.30-latest
    container_name: api-gateway
    ports:
      - "8080:8080" # Main entry point for all frontend traffic
      - "9901:9901" # Envoy Admin & Telemetry Dashboard
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    depends_on:
      - user-service
      - catalog-service

# Persist database records and message queues even if we tear down the containers
volumes:
  mongo-data:
  rabbitmq-data:
